### ISSUE TITLE
Research best GPS to use

### ISSUE THREAD

**Issue by ryanloeffelman** [MST-Robotics/IGVC#32]
Test current GPS, and Research new GPS systems to find the easiest to integrate, and most accurate solution.

**Comment by matthewia94** [comment]
We are going to stick with the Garmin 18x for now.  It should do what we want and is in a simple to use form factor.  If we need to we also have this: https://www.sparkfun.com/products/11058.  Which could be used with an arduino or some type of microcontroller.
