### ISSUE TITLE
Research camera

### ISSUE THREAD

**Issue by matthewia94** [MST-Robotics/IGVC#36]
Our current camera uses firewire which is relatively rare and will likely not be supported on our new computing system.  Ideally we would like to have a usb or IP camera depending on what gives a decent resolution and speed.  It is probably more important to prioritize speed since we will likely blur the image to process it.

This link may be helpful: http://wiki.ros.org/usb_cam

**Comment by ryanloeffelman** [comment]
We are going to use a Logitech C920 http://www.amazon.com/Logitech-Webcam-Widescreen-Calling-Recording/dp/B006JH8T3S/ref=sr_1_1?s=pc&ie=UTF8&qid=1446831286&sr=1-1&keywords=c920
