### ISSUE TITLE
Retrieve data from IMU

### ISSUE THREAD

**Issue by matthewia94** [MST-Robotics/IGVC#40]
This will depend on the electrical division who will need to create a board with an IMU on it.  Data from the IMU should be returned as an imu message.

This link may be helpful: http://docs.ros.org/api/sensor_msgs/html/msg/Imu.html

**Comment by ian-howell** [comment]
IMU datasheets - https://github.com/ptrbrtz/razor-9dof-ahrs/wiki/Tutorial
